lib/main.dart, lib/views/settings_screen/settings_screen_view.dart, linux/flutter/generated_plugin_registrant.cc, linux/flutter/generated_plugins.cmake, macos/Flutter/GeneratedPluginRegistrant.swift, pubspec.lock, pubspec.yaml, windows/flutter/generated_plugin_registrant.cc, windows/flutter/generated_plugins.cmake
With `Alt+Enter` or `Ctrl+F`.
I decided to not make this into a setting (yet) because that will be complicated in multi-screen scenarios.
=> Allow setting full screen mode.

lib/views/capture_screen/capture_screen_view_model.dart, lib/views/custom_widgets/capture_counter.dart, lib/views/multi_capture_screen/multi_capture_screen_view_model.dart
The capture is slightly enhanced by firing the capture at the peak of the flash instead of the start, and by displaying a circular progress indicator that counts down to the moment of capture.
=> Better capture

lib/models/settings.dart, lib/views/settings_screen/settings_screen_controller.dart, lib/views/settings_screen/settings_screen_view.dart, lib/views/settings_screen/settings_screen_view_model.dart, lib/views/share_screen/share_screen_view.dart, lib/views/share_screen/share_screen_view_model.dart, pubspec.lock, pubspec.yaml
Displays confetti on the share screen (if enabled).
What more do you want? ✨
=> Confetti 🎉✨

lib/hardware_control/photo_capturing/live_view_stream_snapshot_capturer.dart, lib/hardware_control/photo_capturing/sony_remote_photo_capture.dart, lib/main.dart, lib/managers/settings_manager.dart, lib/rust_bridge/library_bridge.dart, lib/utils/route_observer.dart, lib/views/capture_screen/capture_screen_view_model.dart, lib/views/collage_maker_screen/collage_maker_screen_controller.dart, lib/views/custom_widgets/photo_collage.dart, lib/views/settings_screen/settings_screen_view.dart, lib/views/settings_screen/settings_screen_view.general.dart, lib/views/settings_screen/settings_screen_view.hardware.dart, lib/views/settings_screen/settings_screen_view.output.dart, lib/views/share_screen/share_screen_controller.dart, pubspec.lock, pubspec.yaml, rust/src/hardware_control/live_view/nokhwa.rs, rust/src/lib.rs
This PR:
- Add Floggy as logging library
- Improves Rust logging interface (adds LogLevel)
- Removes all `print()` statements in favor of Floggy
- Adds Log tab to Settings screen to view log
- Splits Settings tab widgets into separate files
But does not contain:
- Logging to file (Needs simple but custom implementation: https://github.com/infinum/floggy/issues/50)
=> Add logging using Floggy

lib/views/capture_screen/capture_screen_view.dart, lib/views/capture_screen/capture_screen_view_model.dart, lib/views/custom_widgets/photo_collage.dart
This makes sure there is no export before the image is ready.
=> Create & use image decoded callback in collage.

lib/models/settings.dart
This change should fix the settings being reset whenever the format is changed
=> Add default values to settings constructors

lib/main.dart, lib/main.routes.dart, lib/managers/photos_manager.dart, lib/utils/hardware.dart, lib/views/base/fade_transition_page.dart, lib/views/custom_widgets/wrappers/slider_widget.dart, lib/views/gallery_screen/gallery_screen.dart, lib/views/gallery_screen/gallery_screen_controller.dart, lib/views/gallery_screen/gallery_screen_view.dart, lib/views/gallery_screen/gallery_screen_view_model.dart, lib/views/photo_details_screen/photo_details_screen.dart, lib/views/photo_details_screen/photo_details_screen_controller.dart, lib/views/photo_details_screen/photo_details_screen_view.dart, lib/views/photo_details_screen/photo_details_screen_view_model.dart, lib/views/share_screen/share_screen_controller.dart, lib/views/share_screen/share_screen_view.dart, lib/views/share_screen/share_screen_view_model.dart, lib/views/start_screen/start_screen_controller.dart, lib/views/start_screen/start_screen_view.dart
From this gallery it is possible to download or print the photos if you for some reason missed the chance originally.
All print related code has been moved to a utils file.
=> Add gallery screen with previous photo exports

README.md
Actually explain what it's all about.
=> Update README.md with introduction.

.github/workflows/release-linux-appimage-x64.yml, .github/workflows/release-win-x64.yml, .gitignore, lib/rust_bridge/library_bridge.dart, rust/Cargo.lock, rust/Cargo.toml, rust/src/lib.rs
Additionally:
- Add CI/CD steps
- Make sure it only tries to use gphoto2 on Windows and macOS
- Print the gPhoto2 init status to log
=> Add gPhoto2 library to helper library

lib/l10n/app_en.arb, lib/managers/hotkey_manager.dart, lib/managers/live_view_manager.dart, lib/views/custom_widgets/photo_collage.dart, lib/views/multi_capture_screen/multi_capture_screen_view.dart, lib/views/multi_capture_screen/multi_capture_screen_view_model.dart
- Add spinner to multi capture
- Fix minor translation issue
- Add restore live view hotkey (Ctrl/Cmd+R)
- Center single picture layout (should be settings, but we might take a more thorough approach on layouts)
=> Minor fixes and improvements

.vscode/tasks.json, macos/Runner.xcodeproj/project.pbxproj, macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, rust/Cargo.toml, rust/src/hardware_control/live_view/mod.rs, rust/src/lib.rs
Possibly debug only and Apple Silicon only though...
=> Fix compile on macOS

.fvm/fvm_config.json, .github/workflows/pr-ci-app.yml, .github/workflows/release-linux-appimage-x64.yml, .github/workflows/release-macos-x64.yml, .github/workflows/release-win-x64.yml, linux/CMakeLists.txt, macos/Podfile.lock, macos/Runner.xcodeproj/project.pbxproj, macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, pubspec.lock, pubspec.yaml, rust/Cargo.lock, rust/Cargo.toml, windows/CMakeLists.txt, windows/runner/CMakeLists.txt, windows/runner/flutter_window.cpp, windows/runner/main.cpp, windows/runner/runner.exe.manifest, windows/runner/utils.cpp, windows/runner/win32_window.cpp, windows/runner/win32_window.h
Additionally, this PR:
- Upgrades both Dart and Rust packages
- Updates the pipelines
- Upgrades all desktop platforms' build configuration
- Updates the `README.md`
=> Upgrade Flutter to 3.13.0

.github/workflows/pr-ci-app.yml, .github/workflows/release-linux-appimage-x64.yml, .github/workflows/release-macos-x64.yml, .github/workflows/release-win-x64.yml, rust/Cargo.lock
- Always build with `-v` flag passed to `flutter build`
- Add `rust-cache` to Windows pipelines
=> Minor build enhancements

.github/workflows/deploy-documentation.yml, .github/workflows/pr-ci-app-linux-appimage-x64.yml, .github/workflows/pr-ci-app-win-x64.yml, .github/workflows/pr-ci-documentation.yml, .github/workflows/release-linux-appimage-x64.yml, .github/workflows/release-macos-x64.yml, .github/workflows/release-win-x64.yml
- Add Linux PR CI (because it's a lot faster than Windows, will temporarily disable Windows PR CI soon and see if I can have it triggered by a PR comment)
- Add `rust-cache` to Linux pipelines for faster builds
- Upload PR CI artifacts for testing purpose
- Don't run PR CI for release branches
=> Pipeline updates

.github/workflows/pr-ci-app-linux-appimage-x64.yml, .github/workflows/pr-ci-app-win-x64.yml, .github/workflows/release-linux-appimage-x64.yml, .github/workflows/release-macos-x64.yml, .github/workflows/release-win-x64.yml, macos/Podfile.lock
Additionally update macOS Podfile.lock, remove rustfmt from Rust components and add rust-cache to macOS pipeline
=> Add rust target folder to rust-cache workspaces

lib/hardware_control/gphoto2_camera.dart, lib/hardware_control/photo_capturing/live_view_stream_snapshot_capturer.dart, lib/hardware_control/photo_capturing/photo_capture_method.dart, lib/hardware_control/photo_capturing/sony_remote_photo_capture.dart, lib/views/capture_screen/capture_screen_view_model.dart, lib/views/multi_capture_screen/multi_capture_screen_view_model.dart, rust/src/dart_bridge/api.rs, rust/src/hardware_control/live_view/gphoto2.rs, rust/src/lib.rs
Should fix loading up the right file when using JPEG+RAW capturing
=> Add hack for clearning camera events before taking a capture using libphoto2

lib/views/custom_widgets/photo_collage.dart
Should make this a setting eventually
=> Set oneLayout rowSizes to original value

lib/main.dart, lib/managers/mqtt_manager.dart, pubspec.lock, pubspec.yaml
=> Publish actual application version to Home Assistant

lib/l10n/app_en.arb, lib/l10n/app_nl.arb, lib/main.dart, lib/managers/photos_manager.dart, lib/managers/sfx_manager.dart, lib/models/settings.dart, lib/views/custom_widgets/wrappers/slider_widget.dart, lib/views/photo_details_screen/photo_details_screen_controller.dart, lib/views/photo_details_screen/photo_details_screen_view.dart, lib/views/photo_details_screen/photo_details_screen_view_model.dart, lib/views/settings_screen/settings_screen_controller.dart, lib/views/settings_screen/settings_screen_view.ui.dart, lib/views/settings_screen/settings_screen_view_model.dart, lib/views/share_screen/share_screen_controller.dart, lib/views/share_screen/share_screen_view.dart, lib/views/share_screen/share_screen_view_model.dart, rust/.gitignore
This PR:
- Adds progress display for the ffsend upload
- Adds click sfx
- Fixes a bug where capture would fail due to the output folder not existing yet
=> Minor improvements

lib/managers/mqtt_manager.dart, lib/managers/settings_manager.dart, lib/views/settings_screen/settings_screen_view.mqtt_integration.dart
Additionally this PR allows changing the settings by publishing to the `update_settings` topic.
=> Publish app version and settings to MQTT

documentation/book.toml, documentation/mdbook-admonish.css, pubspec.yaml
This PR:
- Should fix the `mdbook-admonish` error when building docs
- Adds docs building scripts to `rps` config
=> Fix building docs

.github/workflows/deploy-documentation.yml, .github/workflows/pr-ci-app-linux-appimage-x64.yml, .github/workflows/pr-ci-app-win-x64.yml, .github/workflows/pr-ci-documentation.yml, .github/workflows/release-linux-appimage-x64.yml, .github/workflows/release-macos-x64.yml, .github/workflows/release-win-x64.yml
This PR combines all GitHub Actions updates from the initial set of Dependabot PRs.
=> Bump actions versions

rust/Cargo.lock, rust/Cargo.toml, rust/src/dart_bridge/api.rs, rust/src/utils/ipp.rs, rust/src/utils/mod.rs
This PR:
- Adds a basic IPP client (for talking to CUPS, the UNIX printing system) by @ccromjongh 
- Adds a few of the IPP client methods to the Dart bridge so we use them from Flutter eventually
=> Add IPP client

lib/views/custom_widgets/image_with_loader_fallback.dart
This PR fixes the memory leak that was caused by ImageWithLoaderFallback adding a listener but never removing it. This might fix the application running slow after a while and should fix the crashes that could occur while or after using the Gallery screen.
=> Fix mem leak in ImageWithLoaderFallback

.github/workflows/pr-ci-app-linux-appimage-x64.yml, .github/workflows/pr-ci-app-win-x64.yml, .github/workflows/release-linux-appimage-x64.yml, .github/workflows/release-macos-x64.yml, .github/workflows/release-win-x64.yml, .vscode/settings.json, README.md, build.yaml, pubspec.lock, pubspec.yaml, rust/Cargo.lock, rust/Cargo.toml, rust_builder/cargokit/build_tool/lib/src/builder.dart
Additionally disable freezed generated code formatting for speedup
=> Upgrade Dart and Rust packages

lib/models/gallery_group.dart, lib/models/gallery_image.dart, lib/models/maker_note_data.dart, lib/models/settings.dart, lib/views/custom_widgets/dialogs/find_face_dialog.dart, lib/views/gallery_screen/gallery_screen_controller.dart, lib/views/gallery_screen/gallery_screen_view.dart, lib/views/gallery_screen/gallery_screen_view_model.dart, lib/views/settings_screen/settings_screen_controller.dart, lib/views/settings_screen/settings_screen_view.dart, lib/views/settings_screen/settings_screen_view.face_recognition.dart, lib/views/settings_screen/settings_screen_view_model.dart, macos/Podfile.lock, macos/Runner.xcodeproj/project.pbxproj, pubspec.lock, pubspec.yaml, rust_builder/macos/rust_lib_momento_booth.podspec
This PR adds support and usage for the Python Image Analyzer which computes the number of people in a picture and encodings for the recognized faces. The number of people can be used to order the pictures. The face encodings can be used to search for images with matching faces on the spot. Both of these features server the purpose of finding "your picture" more quickly 😄.
=> Gallery order and search

lib/hardware_control/photo_capturing/photo_capture_method.dart, lib/hardware_control/photo_capturing/sony_remote_photo_capture.dart, lib/hardware_control/printing/printing_system_client.dart, lib/main.dart, lib/managers/photos_manager.dart, lib/models/settings.dart, lib/utils/file_utils.dart, lib/views/capture_screen/capture_screen_view_model.dart, lib/views/custom_widgets/dialogs/find_face_dialog.dart, lib/views/custom_widgets/image_with_loader_fallback.dart, lib/views/custom_widgets/photo_collage.dart, lib/views/custom_widgets/photo_container.dart, lib/views/multi_capture_screen/multi_capture_screen_view_model.dart, lib/views/photo_details_screen/photo_details_screen_controller.dart, lib/views/photo_details_screen/photo_details_screen_view_model.dart, lib/views/settings_screen/settings_screen_view.hardware.dart, lib/views/share_screen/share_screen_controller.dart, lib/views/share_screen/share_screen_view_model.dart, rust/src/models/images.rs, rust/src/utils/jpeg.rs
This PR:
- Allows overwriting the Sentry DSN using a file named `sentry_dsn_override.txt`  (placed in the same folder as the executable)
- Should fix some file not found errors (which where actually assets, we should now be able to resolve them correctly)
- Should fix some null check errors
- Disables the autofocus before capture functionality by default (as it seems to cause capture errors sometimes, possibly due to us confusing the camera with a command it may not support)
- Change file writes to use locking to make sure any consumers won't operate on partial written files
- Fixes the stored EXIF date to be off by "timezone offset" hours
=> Minor improvements and fixes

rust/Cargo.lock, rust/Cargo.toml
=> Disable nokhwa decoding capabilities for now to fix compile error on Windows

documentation/src/SUMMARY.md, documentation/src/getting_started.md, documentation/src/hardware_compatibility.md, documentation/src/printer_setup.md, documentation/src/settings/page_margins.md, documentation/src/settings/page_size.md, documentation/src/settings/print_grid.md, documentation/src/settings_hardware.md, documentation/src/template_design_guide.md, documentation/src/template_setup.md
The documentation hasn't had any love for a while. It needs some updates.
I already updated some of the printer info and made a guide on how to design templates with MomentoBooth.
=> Docs update

rust/Cargo.lock, rust/Cargo.toml, rust/src/hardware_control/live_view/gphoto2.rs
Also:  Workaround Nikon camera post capture live view errors, remove unused Rust package
=> Enable webcam JPEG decoding support again using a workaround

lib/views/custom_widgets/dialogs/find_face_dialog.dart, lib/views/custom_widgets/dialogs/modal_dialog.dart, lib/views/custom_widgets/dialogs/print_dialog.dart, lib/views/custom_widgets/dialogs/printer_issue_dialog.dart, lib/views/custom_widgets/dialogs/qr_share_dialog.dart, lib/views/custom_widgets/pages/fluent_settings_page.dart, lib/views/gallery_screen/gallery_screen_view.dart, lib/views/settings_screen/settings_screen_view.dart, lib/views/settings_screen/settings_screen_view.debug.dart, lib/views/settings_screen/settings_screen_view.face_recognition.dart, lib/views/settings_screen/settings_screen_view.general.dart, lib/views/settings_screen/settings_screen_view.hardware.dart, lib/views/settings_screen/settings_screen_view.mqtt_integration.dart, lib/views/settings_screen/settings_screen_view.output.dart, lib/views/settings_screen/settings_screen_view.stats.dart, lib/views/settings_screen/settings_screen_view.templating.dart, lib/views/settings_screen/settings_screen_view.ui.dart, lib/views/settings_screen/settings_screen_view_model.dart, lib/views/settings_screen/widgets/file_picker_card.dart, lib/views/settings_screen/widgets/folder_picker_card.dart, lib/views/settings_screen/widgets/update_secret_dialog.dart, pubspec.lock, pubspec.yaml
Fixes any possible licensing issues with Microsoft icons.
=> Initial replacement of all Fluent and FA icons by Lucide icons

lib/theme/momento_booth_theme_data.dart, lib/views/custom_widgets/dialogs/loading_dialog.dart, lib/views/custom_widgets/dialogs/photo_booth_dialog.dart, macos/Podfile.lock, pubspec.lock, pubspec.yaml, rust/Cargo.lock
=> Upgrade packages, remove figma_squircle in favor of builtin Flutter functionality

lib/views/components/imaging/live_view_background.dart, lib/views/photo_booth_screen/components/activity_monitor.dart, lib/views/photo_booth_screen/screens/manual_collage_screen/manual_collage_screen_view.dart
Additionally remove live view (except blurred background) from the Manual Collage screen for better visibility
=> Don't navigate to Home screen when we are in the Settings screen or the Manual Collage screen

CHANGELOG.md, lib/managers/settings_manager.dart, lib/repositories/serializable/toml_serializable_repository.dart, lib/views/base/build_context_abstractor.dart, lib/views/base/photo_booth_dialog_page.dart, lib/views/settings_screen/components/import_field.dart, macos/Podfile.lock
Additionally saving the settings now puts the subsystem in error state when saving has failed.
=> Create initial settings file when no settings file is present

lib/hardware_control/printing/cups_client.dart, lib/views/settings_screen/settings_screen_view_model.dart, rust/Cargo.lock, rust/Cargo.toml, rust/src/api/cups.rs, rust/src/utils/ipp_client.rs
Should make TLS work again like it did earlier. Additionally switch IPP client to async.
=> Re-enable TLS support in IPP client

rust/src/api/initialization.rs
Fix deadlock causing other issues.
=> Fix closing of noise handling on hot restart

CHANGELOG.md, lib/managers/_all.dart, lib/managers/app_init_manager.dart, lib/managers/external_system_status_manager.dart, lib/managers/live_view_manager.dart, lib/managers/mqtt_manager.dart, lib/managers/notifications_manager.dart, lib/managers/printing_manager.dart, lib/managers/project_manager.dart, lib/managers/settings_manager.dart, lib/managers/sfx_manager.dart, lib/managers/stats_manager.dart, lib/managers/wakelock_manager.dart, lib/managers/window_manager.dart, lib/models/settings.dart, lib/views/components/indicators/subsystem_status_list.dart, lib/views/settings_overlay/pages/settings_overlay_view.general.dart, lib/views/settings_overlay/settings_overlay_controller.dart, lib/views/settings_overlay/settings_overlay_view_model.dart, macos/Flutter/GeneratedPluginRegistrant.swift, pubspec.lock, pubspec.yaml
Additionally the Settings and Onboarding UI will now auto enumerate and update the subsystem statuses.
=> Add optional wakelock to try keeping the computer and screen awake
