momentobooth/momentobooth

lib/managers/photos_manager.dart, lib/models/settings.dart, lib/views/capture_screen/capture_screen_view.dart, lib/views/capture_screen/capture_screen_view_model.dart, lib/views/collage_maker_screen/collage_maker_screen_controller.dart, lib/views/collage_maker_screen/collage_maker_screen_view.dart, lib/views/custom_widgets/photo_collage.dart, lib/views/settings_screen/settings_screen_controller.dart, lib/views/settings_screen/settings_screen_view.dart, lib/views/settings_screen/settings_screen_view.helpers.dart, lib/views/settings_screen/settings_screen_view_model.dart, lib/views/share_screen/share_screen_controller.dart, lib/views/share_screen/share_screen_view.dart, lib/views/share_screen/share_screen_view_model.dart, lib/views/start_screen/start_screen_controller.dart, lib/views/start_screen/start_screen_view_model.dart, pubspec.lock, pubspec.yaml
* A directory picker ([using this](https://pub.dev/packages/file_picker)) has been added to the settings screen.
* A template system has been introduced to style processed pictures/collages
* Fore- and background images live in the template directory, selectable in settings.
* A fore- or background image can either be general, or specific to the number of selected images
* Naming system is `{front/back}-template{-#}.{png/jpg}`.
* The collage maker now displays the order of selection for photos instead of a ✔️
* The layout of the collages is slightly improved
* The display of the logo is now a boolean (that is not used yet)  
This could later be used to set a logo without creating front-/background templates.
* Image output is now written enumerated, the last number in the output dir is …
=> Templates & IO

lib/main.dart, lib/views/collage_maker_screen/collage_maker_screen_controller.dart, lib/views/collage_maker_screen/collage_maker_screen_view.dart, lib/views/collage_maker_screen/collage_maker_screen_view_model.dart, lib/views/custom_widgets/photo_collage.dart, lib/views/share_screen/share_screen_controller.dart, lib/views/share_screen/share_screen_view.dart, lib/views/share_screen/share_screen_view_model.dart, lib/views/start_screen/start_screen_view.dart
* The rotation functionality of #71 has been used to properly rotate the collage output
* Possible image rotation is handled in the share print function as well
* Visual feedback when having pressed the print button on the share screen.
* Continue button on collage maker screen can now not be pressed until the rendering is finished.
* Start screen had a little bug where touch was only recognized when touching one of the visible UI elements. This has been fixed.
* The app now automatically navigates home after 45 seconds of inactivity.
* This could be a setting, maybe convenient for during development.
=> Collage output and UX enhancements

lib/views/collage_maker_screen/collage_maker_screen_controller.dart
Well, it is what it is. You could deselect quickly and then get a continue when 0 images were selected.
=> Final small fix for concurrent collage output calls.

lib/main.dart, lib/main.routes.dart, lib/views/base/build_context_abstractor.dart, lib/views/base/fade_transition_page.dart, lib/views/capture_screen/capture_screen_view_model.dart, lib/views/choose_capture_mode_screen/choose_capture_mode_screen_controller.dart, lib/views/collage_maker_screen/collage_maker_screen_controller.dart, lib/views/multi_capture_screen/multi_capture_screen_view_model.dart, lib/views/settings_screen/settings_screen_view.dart, lib/views/share_screen/share_screen_controller.dart, lib/views/start_screen/start_screen_controller.dart, rust/src/lib.rs
This PR:
- Fixes the memory leaking from old screens kept alive due to using `push`/`pop` based navigation
- Adds nice animations to animate between screens
- Fixes the log from the native library not working after hot restart
- Wraps the settings panes with a `Builder` to make sure they don't get rebuild when not needed (fixes state loss while changing settings)
=> Fix memory leaking from old screen state

lib/models/settings.dart, lib/views/settings_screen/settings_screen_controller.dart, lib/views/settings_screen/settings_screen_view.dart, lib/views/settings_screen/settings_screen_view_model.dart, lib/views/share_screen/share_screen_controller.dart
Not as much as a bugfix as I thought it would be, initial problems were related to the printer itself acting weird. Anyway. The centering of the image in the print output is fixed.
Adds settings for sizing and positioning the print as wanted. For inspection, the generated PDF is now also saved to disk as `latest-print.pdf` in the output folder.
=> Fix printing

lib/views/capture_screen/capture_screen_view_model.dart, lib/views/custom_widgets/wrappers/live_view_background.dart, lib/views/multi_capture_screen/multi_capture_screen_view_model.dart
Live view now fades in and out instead of appearing an disappearing in a binary way, which gave a feeling of something having gone wrong. This makes the wait after the flash now also feel less long.
To improve responsiveness even more, the time after moving on from capture has been reduced. The whole flash is not waited for anymore. This is not really noticeable because the opacity is already quite low while the curve remains untouched.
=> Live view fading

lib/views/capture_screen/capture_screen_view.dart, lib/views/custom_widgets/photo_collage.dart
The collage template loading was causing stuttering in the first second of the single capture. This has been solved by making sure it only loads the templates for the single-layout.
Additionally, the decoding load has been spread for "normal" mode, when all templates are loaded.
=> Fix stuttering by collage

lib/models/settings.dart, lib/views/capture_screen/capture_screen_view.dart, lib/views/capture_screen/capture_screen_view_model.dart, lib/views/collage_maker_screen/collage_maker_screen_view.dart, lib/views/collage_maker_screen/collage_maker_screen_view_model.dart, lib/views/custom_widgets/photo_collage.dart, lib/views/settings_screen/settings_screen_controller.dart, lib/views/settings_screen/settings_screen_view.general.dart, lib/views/settings_screen/settings_screen_view.output.dart, lib/views/settings_screen/settings_screen_view_model.dart
After a lot of testing with the printer, it became clear that more control was required to get a good print. Two settings have been added to control image generation such that the desired resulting print can be achieved.
1. Aspect ratio
The photo paper may not be 3:2 exactly, so to make a generated image fit, the aspect ratio has to be correct.
2. Padding
No printer has perfect alignment, so adding a bit of padding helps to prevent white borders showing while retaining the desired layout. The padding is applied _around_ the aspect ratio/content. The back and foregrounds cover the entire area inc. padding.
=> Collage sizing settings

lib/views/share_screen/share_screen_controller.dart, lib/views/share_screen/share_screen_view.dart, lib/views/share_screen/share_screen_view_model.dart
Text button responds immediately and becomes translucent & disabled for 4 seconds. Then clearly shows another print will be started by pressing.
=> Print button gives more feedback

.github/workflows/release-win-x64.yml, lib/hardware_control/gphoto2_camera.dart, lib/hardware_control/live_view_streaming/gphoto2_camera.dart, lib/main.dart, lib/managers/live_view_manager.dart, lib/models/settings.dart, lib/models/settings.enums.dart, lib/rust_bridge/library_bridge.dart, lib/views/capture_screen/capture_screen_view.dart, lib/views/capture_screen/capture_screen_view_model.dart, lib/views/multi_capture_screen/multi_capture_screen_view_model.dart, lib/views/settings_screen/settings_screen_controller.dart, lib/views/settings_screen/settings_screen_view.hardware.dart, lib/views/settings_screen/settings_screen_view_model.dart, pubspec.lock, pubspec.yaml, rust/Cargo.lock, rust/Cargo.toml, rust/src/dart_bridge/api.rs, rust/src/hardware_control/live_view/gphoto2.rs, rust/src/hardware_control/live_view/mod.rs, rust/src/lib.rs
This PR:
- Adds basic gPhoto2 support (atleast on Windows, Linux untested, macOS doesn't seem to compile at the moment)
- Adds support for specific Nikon DSLR commands (for live view enable, auto focus trigger)
- Add support for live view and HQ capture
- Adds a circular progress bar during capture photo load (only in single capture mode)
- Adds a step to the Windows build pipeline to bundle the necessary additional DLLs
- Updates some Dart and Rust packages
=> Basic gPhoto2 support

.github/workflows/release-win-x64.yml, lib/main.dart, lib/views/settings_screen/settings_screen_view.dart, lib/views/settings_screen/settings_screen_view_model.dart, pubspec.yaml
This PR:
- Undos the translations (not available) fix for the settings screen and adds a new fix that should not interfere with popups/overlays used by `fluent_ui` components in the Settings screen
- Adds default paths (as Dart defines) for the supporting libraries for libgphoto2, this should help the app find the right libraries in production independently from whatever environment variables are set globally
Still TODO: Actually bundle these supporting libraries...
=> gPhoto2 environment variables and Settings screen fix

.github/workflows/pr-ci-app.yml, .github/workflows/release-linux-appimage-x64.yml, .github/workflows/release-macos-x64.yml, .github/workflows/release-win-x64.yml, lib/views/capture_screen/capture_screen_view.dart, lib/views/collage_maker_screen/collage_maker_screen_view.dart, lib/views/custom_widgets/image_with_loader_fallback.dart, lib/views/custom_widgets/photo_collage.dart, lib/views/manual_collage_screen/manual_collage_screen_view.dart, lib/views/settings_screen/settings_screen_view.templating.dart, lib/views/share_screen/share_screen_view.dart, pubspec.lock, pubspec.yaml, rust/Cargo.lock, rust/Cargo.toml
The PR:
- Workarounds the black collage image issue (image captured from camera appearing fully black in capture) by awaiting the postFrameCallback once
- Cleans up the PhotoCollage widget and related code
- Updates Flutter and Rust packages
=> Cleanup PhotoCollage widget and simplify using it properly

.github/workflows/pr-ci-app.yml, .github/workflows/release-win-x64.yml, analysis_options.yaml, distribute_options.yaml, lib/hardware_control/gphoto2_camera.dart, lib/models/settings.dart, lib/views/settings_screen/settings_screen_controller.dart, lib/views/settings_screen/settings_screen_view.hardware.dart, lib/views/settings_screen/settings_screen_view_model.dart, rust/src/dart_bridge/api.rs, rust/src/hardware_control/live_view/gphoto2.rs
Kinda experimental but when you leave the setting empty, it will not try to send the config change to the camera.
Works at least for D3400 when using "Memory card" as value.
=> Add gphoto2 capturetarget setting

lib/managers/mqtt_manager.dart, lib/managers/settings_manager.dart, lib/models/home_assistant/home_assistant_discovery_payload.dart, lib/models/home_assistant/home_assistant_integration_type.dart, lib/models/settings.dart, lib/utils/random_string.dart, lib/views/settings_screen/settings_screen_controller.dart, lib/views/settings_screen/settings_screen_view.mqtt_integration.dart, lib/views/settings_screen/settings_screen_view_model.dart
This PR:
- Optimizes the MQTT topic settings defaults and MQTT topic names (inspired by the great Zigbee2MQTT)
- Adds the publishing of discovery topics for Home Assistant for sensors and triggers
- Adds the new Home Assistant related settings to the Settings UI
=> Home Assistant integration

lib/hardware_control/gphoto2_camera.dart, lib/hardware_control/live_view_streaming/live_view_source.dart, lib/hardware_control/live_view_streaming/noise_source.dart, lib/hardware_control/live_view_streaming/nokhwa_camera.dart, lib/hardware_control/photo_capturing/live_view_stream_snapshot_capturer.dart, lib/hardware_control/photo_capturing/photo_capture_method.dart, lib/models/settings.dart, lib/views/settings_screen/settings_screen_controller.dart, lib/views/settings_screen/settings_screen_view.hardware.dart, lib/views/settings_screen/settings_screen_view.helpers.dart, lib/views/settings_screen/settings_screen_view.templating.dart, lib/views/settings_screen/settings_screen_view_model.dart, rust/src/dart_bridge/api.rs, rust/src/hardware_control/live_view/gphoto2.rs
This PR:
- Changes the Rust-to-Dart interface to send over camera file info from gphoto2
- Allows saving captured photos to disk
- Allows saving additional available photos (e.g. RAW when using JPEG+RAW camera setting) to disk
- Should not change anything for the Sony Imaging Edge automation capture method
- Cleanups Settings screen code and makes sure some hardware settings are only available when certain capture method is selected
=> Allow saving captures photos to disk

.fvm/fvm_config.json, lib/models/settings.dart, lib/models/settings.enums.dart, lib/views/custom_widgets/wrappers/lottie_animation_wrapper.dart, lib/views/start_screen/start_screen_view.dart, lib/views/start_screen/start_screen_view_model.dart, pubspec.lock, pubspec.yaml, rust/Cargo.lock
This PR:
- Adds Lottie animations to the Start screen
- Updates Flutter to 3.13.7 and upgrades packages
Still TODO:
- Allow anchoring the animation to elements like the MomentoBooth logo or the "Tap to start" text
- Settings UI for the animations (edit the TOML settings file for now...)
=> Add Lottie animations to start screen, update Flutter and packages

lib/main.dart, lib/managers/live_view_manager.dart, lib/managers/stats_manager.dart, lib/models/settings.dart, lib/views/capture_screen/capture_screen_view.dart, lib/views/collage_maker_screen/collage_maker_screen_view.dart, lib/views/custom_widgets/capture_counter.dart, lib/views/custom_widgets/photo_collage.dart, lib/views/custom_widgets/wrappers/live_view_background.dart, lib/views/custom_widgets/wrappers/lottie_animation_wrapper.dart, lib/views/gallery_screen/gallery_screen_view.dart, lib/views/manual_collage_screen/manual_collage_screen_view.dart, lib/views/multi_capture_screen/multi_capture_screen_view.dart, lib/views/photo_details_screen/photo_details_screen_view.dart, lib/views/settings_screen/settings_screen_controller.dart, lib/views/settings_screen/settings_screen_view.debug.dart, lib/views/settings_screen/settings_screen_view_model.dart, lib/views/share_screen/share_screen_view.dart, lib/views/start_screen/start_screen_view.dart, macos/Flutter/GeneratedPluginRegistrant.swift, macos/Podfile.lock, pubspec.lock, pubspec.yaml, rust/Cargo.lock, rust/Cargo.toml, rust/src/dart_bridge/api.rs, rust/src/hardware_control/live_view/gphoto2.rs, rust/src/hardware_control/live_view/white_noise.rs
This PR:
- Disables clipping for all Stack widgets that don't need it anyway
- Adds an FPS counter (enable from Settings -> Debug tab)
- Cleansup and simplifies the LiveView widget
- Locks flutter_rust_bridge at Rust side to the correct version that's also used by Dart
- Updates macOS build files
- Updates packages
- Deduplicate gphoto2 frames by hash value + 8 ms delay every time a duplicate frame is detected
=> Performance improvements and FPS counter

lib/managers/mqtt_manager.dart
This PR:
- Fixes listening to MQTT messages, should fix getting retained messages we are not subscribed to
- Upgrades Flutter to 3.13.8
- Upgrades Flutter and Rust packages
=> Flutter and Rust updates, MQTT fix

lib/app/shell/shell.dart, rust/src/hardware_control/live_view/gphoto2.rs
This PR:
- Adds a universal (but blocking while waiting for the result, it seems) autofocus trigger method
- Fixes closing the gPhoto2 camera handle (restoring the camera's state) when closing the app window
=> Multiple fixes

lib/views/custom_widgets/photo_collage.dart, lib/views/manual_collage_screen/manual_collage_screen_view.dart, lib/views/settings_screen/settings_screen_view.templating.dart, lib/views/settings_screen/settings_screen_view_model.dart
Mostly what the title says.
The middleground (photo layer) can now be toggled off in the template debug screen for easier creation or debugging of templates.
`cacheWidth` has been added to the images in the manual collage screen to make it faster.
=> Template debug middleground toggle and image cache for manual collage screen

.github/workflows/pr-ci-app-win-x64.yml, .github/workflows/release-win-x64.yml, rust/Cargo.lock, rust_builder/cargokit/build_tool/lib/src/builder.dart, rust_builder/cargokit/build_tool/lib/src/target.dart
This PR:
- Replaces use of mingw64 libs by clang64 libs
- Changes build settings to build on MSVC instead of GNU
- Requires some changes on developer PCs which I will document in a separate PR
Note: This should only change things on Windows.
=> Build using MSVC on Windows, adapt Windows pipelines

lib/hardware_control/gphoto2_camera.dart, lib/main.dart, lib/managers/helper_library_initialization_manager.dart, lib/managers/live_view_manager.dart, lib/utils/file_utils.dart, lib/utils/hardware.dart, lib/views/settings_screen/settings_screen_controller.dart, rust/Cargo.lock, rust/Cargo.toml, rust/src/api/initialization.rs, rust/src/api/noise.rs, rust/src/hardware_control/live_view/gphoto2.rs, rust/src/hardware_control/live_view/nokhwa.rs, rust/src/helpers.rs, rust/src/utils/flutter_texture.rs
This PR:
- Fixes an issue where printer status detection could not log
- Fixes errors in the camera status check that occurred when the camera wasn't opened yet
- Creates any file system paths used by the application in order to fix errors due to non existing directories
- Removes custom Rust-to-Dart log tunneling method in favor of `flutter_logger`, any gPhoto2 log messages should now appear in the application log found in the Settings screen
=> Improve logging

.github/workflows/pr-ci-app-win-x64-libgphoto2-from-git.yml
This PR adds a hacked together variant of the Windows PR CI pipeline script, that builds libgphoto2 from the latest git master instead of using the MSYS2/Clang64 package. This allows for testing whether a future libgphoto2 version will fix a certain issue and if it's still compatible with the Rust wrapper and MomentoBooth.
=> Add PR CI script to build libgphoto2 from git

.vscode/launch.json, lib/extensions/string_extension.dart, lib/models/settings.dart, lib/views/settings_screen/settings_screen_controller.dart, lib/views/settings_screen/settings_screen_view.ui.dart, lib/views/settings_screen/settings_screen_view_model.dart, lib/views/start_screen/start_screen_view.dart, lib/views/start_screen/start_screen_view_model.dart
If you set this to a custom text ...
the start screen will now look like this:
A long text just to show what happens:
=> Allow overriding the default 'Touch to Start' text

.github/workflows/pr-ci-app-macos-arm64.yml, .github/workflows/pr-ci-app-win-x64.yml, .github/workflows/release-linux-appimage-x64.yml, .github/workflows/release-win-x64.yml, macos/Podfile.lock, pubspec.lock, pubspec.yaml, rust/Cargo.lock, rust/Cargo.toml
This PR:
- Updates the Dart and Rust dependencies
- Raises the .zip compression level for Windows pipelines to make packages smaller
- Removes the `Podfile.lock` prior to building the macOS version, forcing it to be recreated; It then commits any changes to the macOS build folder to make sure the macOS build files are up to date
=> Update dependencies, have GH Actions automatically update macOS build files when necessary

.github/workflows/pr-ci-app-linux-appimage-x64.yml, .github/workflows/pr-ci-app-macos-arm64.yml, .github/workflows/pr-ci-app-win-x64.yml, .github/workflows/release-linux-appimage-x64.yml, .github/workflows/release-macos-x64.yml, .github/workflows/release-win-x64.yml, justfile, linux/flutter/generated_plugin_registrant.cc, linux/flutter/generated_plugins.cmake, macos/Flutter/GeneratedPluginRegistrant.swift, macos/Podfile.lock, pubspec.lock, pubspec.yaml, rust/Cargo.lock, rust/Cargo.toml, windows/flutter/generated_plugin_registrant.cc, windows/flutter/generated_plugins.cmake
For now, I haven't paid attention to:
- ipp 5.1.0
- little_exif 0.6.2
As they cause API breakage. These will be addressed in a future PR.
=> Upgrade Dart and Rust packages, upgrade FRB to 2.6.0

README.md
Correct the version of `flutter_rust_bridge_codegen` in the documentation to reflect the latest release.
=> Update FRB version in README.md

.github/workflows/pr-ci-app-linux-appimage-x64.yml, .github/workflows/pr-ci-app-macos-arm64.yml, .github/workflows/pr-ci-app-win-x64.yml, .github/workflows/release-linux-appimage-x64.yml, .github/workflows/release-macos-arm64.yml, .github/workflows/release-win-x64.yml, .vscode/settings.json, lib/views/settings_screen/settings_screen.dart, lib/views/settings_screen/settings_screen_view.dart, linux/CMakeLists.txt, pubspec.lock, rust/Cargo.lock
This PR:
- Updates dependencies
- Removes the creation of a custom dev drive in the Windows pipelines (as there is no actual benefit)
- Enables mimalloc for the Linux builds (as [advised](https://github.com/media-kit/media-kit?tab=readme-ov-file#utilize-mimalloc) by media-kit)
- Update Rust caching paths in the macOS pipelines to hopefully speed up builds
- Adds a (currently not yet utilized) method for opening the Settings screen on any given page
- Adds uploading of the custom libgphoto2 MSYS2 package as artifact, for verification and issue reproducibility
=> Fix minor pipelines and build issues

lib/managers/photos_manager.dart, lib/models/_all.dart, lib/models/constants.dart, lib/views/components/dialogs/find_face_dialog.dart, lib/views/photo_booth_screen/screens/capture_screen/capture_screen_view_model.dart, lib/views/photo_booth_screen/screens/multi_capture_screen/multi_capture_screen_view_model.dart
The code to initiate a delayed capture was duplicated in both the single- and multi-capture screens.
This PR solves that by moving the capture logic (including time calculation) to the `PhotosManager`. The `FindFaceDialog`'s code has also been simplified with this change. A custom countdown delay was used there before, so the option for this is also implemented in the new method.
The timing division is now as follows:
The flash in the _capture screens_ is activated after the counter ends (# of seconds set in settings).
The actual capture delay is now calculated in the `PhotosManager`. As before, it takes the countdown length, flash, and capture delay time (caused by e.g. focussing) into account.
=> Deduplicate capture code

lib/models/gallery_image.dart, lib/views/photo_booth_screen/screens/gallery_screen/gallery_screen_view_model.dart
Because of the changes introduced in #389 to improve upon #365, a null check operator could be used on a null value in the generation of the title for the `GalleryGroup`s.
Since the for the `creationDate` is sourced from the EXIF data, and PNG images do not have EXIF data, this failed and the title of the group could not be constructed.
This PR solves this by using the **file**'s modified date as a fallback for when no EXIF data is present.
=> Fix gallery empty screen when PNGs are present in output folder

.github/workflows/pr-ci-app-win-x64.yml, .github/workflows/release-win-x64.yml, windows/bundle_libs.ps1
Additionally move the script to a separate file
=> Fix the Windows pipeline bundling script not crashing on missing DLL's

.github/workflows/pr-ci-app-linux-appimage-x64.yml, .github/workflows/pr-ci-app-macos-arm64.yml, .github/workflows/pr-ci-app-win-x64.yml, .github/workflows/release-linux-appimage-x64.yml, .github/workflows/release-macos-arm64.yml, .github/workflows/release-win-x64.yml, lib/main.dart, lib/managers/external_system_status_manager.dart, lib/managers/live_view_manager.dart, lib/managers/mqtt_manager.dart, lib/managers/notifications_manager.dart, lib/managers/printing_manager.dart, lib/managers/project_manager.dart, lib/managers/settings_manager.dart, lib/managers/sfx_manager.dart, lib/managers/stats_manager.dart, lib/managers/window_manager.dart, lib/models/_all.dart, lib/models/external_system_status.dart, lib/models/settings.dart, lib/models/settings.enums.dart, lib/models/subsystem.dart, lib/models/subsystem_status.dart, lib/views/settings_overlay/pages/settings_overlay_view.subsystem_status.dart, lib/views/settings_overlay/settings_overlay_controller.dart, lib/views/settings_overlay/settings_overlay_view.dart, lib/views/settings_overlay/settings_overlay_view_model.dart
The correct functioning of the photobooth set-up is often not only reliant on the MomentoBooth software itself, but also on other systems or services. Therefore, this PR introduces a health check mechanism for external systems.
In the **subsystem status** page of the settings, you can now set up health monitors for external systems. Checking is supported through **ping** and **HTTP request**. These are executed by a new external system status manager. For each check, you can specify a severity and disable it if it is not relevant at that moment in time.
The notifications manager had a little makeover to display notifications (called InfoBar by FluentUI) for all subsystems and external systems, ordered by severity.
=> Systems health check

lib/main.dart, lib/managers/app_init_manager.dart, lib/managers/project_manager.dart, lib/momento_booth_app.dart, lib/momento_booth_app.hotkeys.dart, lib/momento_booth_app.routes.dart, lib/views/components/indicators/onboarding_version_info.dart, lib/views/onboarding_screen/components/wizard_page.dart, lib/views/onboarding_screen/onboarding_screen.dart, lib/views/onboarding_screen/pages/error_page.dart, lib/views/onboarding_screen/pages/initialization_page.dart, lib/views/onboarding_screen/pages/status_page.dart, lib/views/onboarding_screen/pages/welcome_page.dart, pubspec.lock, pubspec.yaml
This PR introduces phase 1 of the onboarding improvements for our first stable release.
It moves the initialization logic from `main.dart` into a dedicated `AppInitManager`.
Benefits:
- Initialization is no longer fire-and-forget — its progress and success can now be tracked via the UI.
- Subsystem initialization is capped at 5 seconds. If a subsystem takes longer, the next page of the onboarding UI will indicate which one is still in progress.
=> Refactor initialization for better observability

.github/workflows/pr-ci-app-win-x64.yml, .github/workflows/release-win-x64.yml, windows/bundle_libs.ps1
Additionally added a basic check that verifies whether `libgphoto2-6.dll` has been copied over to detect whether the bundle script has done anything.
=> Fix Windows library bundle script not bundling libraries
